import { Question } from '@/types/wizard';
import { createQuestion } from '@/utils/wizard';

export const websiteBriefQuestions: Question[] = [
  // ================= SECTION: WELCOME =================
  createQuestion({
    id: 'welcome_intro',
    type: 'heading',
    title: '👋 Welcome to Website Brief Wizard',
    description: 'We are thrilled to work with you! Instead of long, messy WhatsApp threads, this simple wizard will guide you to provide structured requirements. This will help us build the perfect solution for your business in less time.',
    section: 'welcome',
  }),

  // ================= SECTION: BUSINESS =================
  createQuestion({
    id: 'business_name',
    type: 'text',
    title: 'Business Name',
    description: 'What is the name of your company or brand?',
    placeholder: 'e.g. Acme Corporation',
    required: true,
    section: 'business',
    width: 'half',
  }),
  createQuestion({
    id: 'business_category',
    type: 'select',
    title: 'Business Category',
    description: 'Select your industry sector.',
    required: true,
    section: 'business',
    width: 'half',
    options: [
      { label: 'Food & Beverage', value: 'fnb' },
      { label: 'Retail & E-Commerce', value: 'retail' },
      { label: 'Healthcare & Medical', value: 'healthcare' },
      { label: 'Professional Services', value: 'services' },
      { label: 'Real Estate', value: 'real_estate' },
      { label: 'Technology & SaaS', value: 'tech' },
      { label: 'Education', value: 'education' },
      { label: 'Other', value: 'other' },
    ],
  }),
  createQuestion({
    id: 'business_description',
    type: 'textarea',
    title: 'Business Description',
    description: 'Tell us briefly what your company does and what you sell.',
    placeholder: 'Describe your core business...',
    required: true,
    section: 'business',
    width: 'full',
  }),
  createQuestion({
    id: 'company_size',
    type: 'select',
    title: 'Company Size',
    description: 'How many employees do you have?',
    section: 'business',
    width: 'half',
    options: [
      { label: '1 - 10 people', value: '1-10' },
      { label: '11 - 50 people', value: '11-50' },
      { label: '51 - 200 people', value: '51-200' },
      { label: '200+ people', value: '200+' },
    ],
  }),
  createQuestion({
    id: 'years_in_business',
    type: 'number',
    title: 'Years in Business',
    placeholder: 'e.g. 5',
    section: 'business',
    width: 'half',
  }),
  createQuestion({
    id: 'location',
    type: 'text',
    title: 'Company Location',
    placeholder: 'e.g. Jakarta, Indonesia',
    required: true,
    section: 'business',
    width: 'half',
  }),
  createQuestion({
    id: 'contact_email',
    type: 'email',
    title: 'Contact Email',
    placeholder: 'e.g. hello@acme.com',
    required: true,
    section: 'business',
    width: 'half',
  }),
  createQuestion({
    id: 'contact_whatsapp',
    type: 'phone',
    title: 'WhatsApp Number',
    placeholder: 'e.g. +62 812-3456-7890',
    required: true,
    section: 'business',
    width: 'half',
  }),
  createQuestion({
    id: 'existing_website',
    type: 'url',
    title: 'Current Website URL (if any)',
    placeholder: 'e.g. https://acme.com',
    section: 'business',
    width: 'half',
  }),

  // ================= SECTION: GOALS =================
  createQuestion({
    id: 'website_type',
    type: 'card-selector',
    title: 'What type of website do you need?',
    description: 'Select the primary format that fits your project goal.',
    required: true,
    section: 'goals',
    options: [
      { label: 'Company Profile', value: 'company_profile', description: 'Informational site representing a business.', icon: 'Building' },
      { label: 'Landing Page', value: 'landing_page', description: 'Single-page layout focused on conversions or leads.', icon: 'Layout' },
      { label: 'E-Commerce Store', value: 'ecommerce', description: 'Selling products online with cart and payments.', icon: 'ShoppingBag' },
      { label: 'Web Application', value: 'web_app', description: 'Complex interactive system with user dashboards.', icon: 'AppWindow' },
      { label: 'Booking / Reservation', value: 'booking', description: 'Appointment slots, calendars, and schedules.', icon: 'CalendarDays' },
      { label: 'Portfolio', value: 'portfolio', description: 'Displaying creative works, photos, or projects.', icon: 'Briefcase' },
      { label: 'Other / Custom', value: 'other', description: 'Something unique not listed above.', icon: 'PlusCircle' },
    ],
  }),
  // Conditional: E-commerce Specifics
  createQuestion({
    id: 'ecommerce_product_count',
    type: 'select',
    title: 'Estimated Product Count',
    description: 'How many items will be listed on the e-commerce store?',
    required: true,
    section: 'goals',
    width: 'half',
    condition: { field: 'website_type', operator: 'equals', value: 'ecommerce' },
    options: [
      { label: '1 - 20 products', value: '1-20' },
      { label: '21 - 100 products', value: '21-100' },
      { label: '101 - 500 products', value: '101-500' },
      { label: '500+ products', value: '500+' },
    ],
  }),
  createQuestion({
    id: 'ecommerce_payment_gateway',
    type: 'select',
    title: 'Preferred Payment Gateway',
    description: 'Select how you want to accept client payments.',
    section: 'goals',
    width: 'half',
    condition: { field: 'website_type', operator: 'equals', value: 'ecommerce' },
    options: [
      { label: 'Midtrans (Recommended for Indo)', value: 'midtrans' },
      { label: 'Xendit', value: 'xendit' },
      { label: 'Stripe', value: 'stripe' },
      { label: 'PayPal', value: 'paypal' },
      { label: 'Manual Bank Transfer Only', value: 'manual' },
      { label: 'Other', value: 'other' },
    ],
  }),
  // Conditional: Booking Specifics
  createQuestion({
    id: 'booking_type',
    type: 'select',
    title: 'What needs to be booked?',
    required: true,
    section: 'goals',
    width: 'half',
    condition: { field: 'website_type', operator: 'equals', value: 'booking' },
    options: [
      { label: 'Services / Appointments (e.g. Salon, Consulting)', value: 'appointment' },
      { label: 'Rooms / Accommodations (e.g. Hotel, Villa)', value: 'accommodation' },
      { label: 'Tickets / Events (e.g. Workshops, Concerts)', value: 'event' },
      { label: 'Other', value: 'other' },
    ],
  }),
  // Conditional: Web App Specifics
  createQuestion({
    id: 'webapp_auth_required',
    type: 'switch',
    title: 'Requires User Authentication / Membership?',
    description: 'Do users need to sign up, log in, and manage their profiles?',
    defaultValue: false,
    section: 'goals',
    width: 'half',
    condition: { field: 'website_type', operator: 'equals', value: 'web_app' },
  }),

  // ================= SECTION: AUDIENCE =================
  createQuestion({
    id: 'target_audience_age',
    type: 'multiselect',
    title: 'Target Audience Age Group',
    description: 'Select all age brackets that apply to your target market.',
    section: 'audience',
    width: 'half',
    options: [
      { label: 'Teens (13 - 18)', value: 'teens' },
      { label: 'Young Adults (19 - 25)', value: 'young_adults' },
      { label: 'Adults (26 - 45)', value: 'adults' },
      { label: 'Seniors (46+)', value: 'seniors' },
    ],
  }),
  createQuestion({
    id: 'target_audience_type',
    type: 'select',
    title: 'Customer Type',
    required: true,
    section: 'audience',
    width: 'half',
    options: [
      { label: 'B2C (Business to Consumer)', value: 'b2c' },
      { label: 'B2B (Business to Business)', value: 'b2b' },
      { label: 'Both B2C and B2B', value: 'both' },
    ],
  }),
  createQuestion({
    id: 'unique_selling_point',
    type: 'textarea',
    title: 'What is your Unique Selling Point (USP)?',
    description: 'Why should customers choose your business over competitors?',
    placeholder: 'We are unique because...',
    section: 'audience',
    width: 'full',
  }),
  createQuestion({
    id: 'competitors',
    type: 'textarea',
    title: 'Competitors',
    description: 'List 2-3 competitor names or websites.',
    placeholder: 'e.g. competitorA.com, competitorB.com',
    section: 'audience',
    width: 'full',
  }),

  // ================= SECTION: BRANDING =================
  createQuestion({
    id: 'has_logo',
    type: 'radio',
    title: 'Do you already have a Logo?',
    required: true,
    section: 'branding',
    width: 'half',
    options: [
      { label: 'Yes, I have it ready', value: 'yes' },
      { label: 'No, I need a logo designed', value: 'no' },
    ],
  }),
  createQuestion({
    id: 'has_brand_guideline',
    type: 'radio',
    title: 'Do you already have a Brand Guideline?',
    description: 'Includes colors, typography scales, spacing rules.',
    required: true,
    section: 'branding',
    width: 'half',
    options: [
      { label: 'Yes, I have it ready', value: 'yes' },
      { label: 'No, I need one created', value: 'no' },
    ],
  }),
  createQuestion({
    id: 'preferred_colors',
    type: 'tags',
    title: 'Preferred Colors',
    description: 'List your desired brand colors or hex values.',
    placeholder: 'e.g. Deep Blue, #FF5733, Warm Gold',
    section: 'branding',
    width: 'full',
  }),

  // ================= SECTION: FEATURES =================
  createQuestion({
    id: 'features_list',
    type: 'multiselect',
    title: 'Select Required Features',
    description: 'Select all features you need on your website.',
    section: 'features',
    width: 'full',
    options: [
      { label: 'Contact Form', value: 'contact_form', description: 'Simple contact form for client inquiries.' },
      { label: 'WhatsApp Chat Integration', value: 'whatsapp_chat', description: 'Direct floating chat widget to WhatsApp.' },
      { label: 'Blog / Articles', value: 'blog', description: 'Publish articles, news, or tutorials.' },
      { label: 'CMS (Content Management System)', value: 'cms', description: 'Ability to edit text and images yourself.' },
      { label: 'User Authentication', value: 'auth', description: 'User registration, login, and profile dashboards.' },
      { label: 'Payment Gateway', value: 'payment_gateway', description: 'Collect credit card, e-wallet payments online.' },
      { label: 'Photo/Video Gallery', value: 'gallery', description: 'Grid layouts for showcasing portfolios/media.' },
      { label: 'Google Maps Integration', value: 'maps', description: 'Embed maps indicating shop locations.' },
      { label: 'Newsletter Subscription', value: 'newsletter', description: 'Allow users to sign up for email updates.' },
      { label: 'Booking System', value: 'booking', description: 'Schedules, calendars, appointments.' },
      { label: 'Multi-Language Support', value: 'multi_language', description: 'Translate content into multiple languages.' },
      { label: 'SEO Setup', value: 'seo', description: 'Meta tags, sitemaps, keywords setup.' },
      { label: 'Google Analytics', value: 'analytics', description: 'Track visitor traffic and behaviors.' },
      { label: 'Internal Search Engine', value: 'search', description: 'Search bar for searching products/blogs.' },
      { label: 'Live Chat Widget', value: 'live_chat', description: 'Realtime chat support widget.' },
      { label: 'AI Assistance', value: 'ai_feature', description: 'Custom AI bots or features.' },
    ],
  }),
  createQuestion({
    id: 'custom_features_input',
    type: 'textarea',
    title: 'Additional Features or Custom Integrations',
    description: 'Detail any specific tools or software you need this site to connect with.',
    placeholder: 'e.g. Syncing stock levels with my offline ERP system...',
    section: 'features',
    width: 'full',
  }),

  // ================= SECTION: DESIGN =================
  createQuestion({
    id: 'design_style',
    type: 'multiselect',
    title: 'Preferred Design Style',
    description: 'Select styles that align with your vision.',
    section: 'design',
    width: 'full',
    options: [
      { label: 'Minimalist & Clean', value: 'minimal', description: 'Lots of whitespace, elegant typography, simple structure.' },
      { label: 'Luxury & Premium', value: 'luxury', description: 'Sophisticated fonts, rich textures, dark/gold themes.' },
      { label: 'Corporate & Professional', value: 'corporate', description: 'Organized structures, trustworthy colors, standard corporate layout.' },
      { label: 'Modern & Futuristic', value: 'modern', description: 'Gradients, micro-interactions, bold visual effects.' },
      { label: 'Playful & Creative', value: 'playful', description: 'Vibrant colors, hand-drawn elements, animations.' },
      { label: 'Dark Mode Focus', value: 'dark', description: 'Primarily dark background, glowing highlights.' },
    ],
  }),
  createQuestion({
    id: 'reference_websites',
    type: 'textarea',
    title: 'Reference Websites',
    description: 'List 2-3 website links that you really like (and explain what you like about them).',
    placeholder: 'e.g. apple.com (sleek layouts), stripe.com (gradients and transitions)',
    section: 'design',
    width: 'full',
  }),
  createQuestion({
    id: 'animation_preference',
    type: 'select',
    title: 'Animation Preference',
    description: 'How much animation should be present on pages?',
    section: 'design',
    width: 'half',
    options: [
      { label: 'None - Static and fast loading', value: 'none' },
      { label: 'Subtle - Gentle fade-ins and hovers (Recommended)', value: 'subtle' },
      { label: 'Dynamic - Scroll transitions, parallax effects', value: 'dynamic' },
    ],
  }),
  createQuestion({
    id: 'project_budget',
    type: 'select',
    title: 'Project Budget Range',
    description: 'Please select your estimated budget range (this helps us tailormake the solution).',
    required: true,
    section: 'design',
    width: 'half',
    options: [
      { label: 'Rp 5M - 15M', value: '5m-15m' },
      { label: 'Rp 15M - 35M', value: '15m-35m' },
      { label: 'Rp 35M - 75M', value: '35m-75m' },
      { label: 'Rp 75M+', value: '75m+' },
    ],
  }),
  createQuestion({
    id: 'project_deadline',
    type: 'select',
    title: 'Estimated Target Deadline',
    description: 'When do you hope to launch the website?',
    required: true,
    section: 'design',
    width: 'half',
    options: [
      { label: 'Urgent (< 3 weeks)', value: 'urgent' },
      { label: 'Standard (1 - 2 months)', value: 'standard' },
      { label: 'Flexible (3+ months)', value: 'flexible' },
    ],
  }),

  // ================= SECTION: ASSETS =================
  createQuestion({
    id: 'upload_logo_files',
    type: 'file-upload',
    title: 'Upload Logo Files',
    description: 'Upload your vector logo (.svg, .ai) or high-res images (.png). Max 50MB.',
    section: 'assets',
    width: 'full',
    condition: { field: 'has_logo', operator: 'equals', value: 'yes' },
  }),
  createQuestion({
    id: 'upload_brand_guidelines_files',
    type: 'file-upload',
    title: 'Upload Brand Guideline Document',
    description: 'Upload brand books, guidelines, or style guides (.pdf, .zip). Max 50MB.',
    section: 'assets',
    width: 'full',
    condition: { field: 'has_brand_guideline', operator: 'equals', value: 'yes' },
  }),
  createQuestion({
    id: 'upload_reference_assets',
    type: 'file-upload',
    title: 'Upload Reference Designs or Layouts',
    description: 'Upload any PDF briefs, wireframes, screenshots, or mood board ZIPs. Max 50MB.',
    section: 'assets',
    width: 'full',
  }),
];
