import { Question } from '@/types/wizard';
import { createQuestion } from '@/utils/wizard';

export const websiteBriefQuestions: Question[] = [
  // ================= SECTION: WELCOME =================
  createQuestion({
    id: 'welcome_intro',
    type: 'heading',
    title: '👋 Selamat Datang di Asisten Project Brief',
    description: 'Kami sangat senang bisa bekerja sama dengan Anda! Untuk menggantikan obrolan WhatsApp yang panjang dan tidak terstruktur, asisten cerdas ini akan memandu Anda menyusun kebutuhan website Anda secara rapi. Ini membantu kami memahami visi Anda dan memberikan penawaran harga yang akurat lebih cepat.',
    section: 'welcome',
  }),

  // ================= SECTION: BUSINESS =================
  createQuestion({
    id: 'business_name',
    type: 'text',
    title: 'Nama Bisnis / Brand',
    description: 'Apa nama perusahaan, bisnis, atau brand Anda?',
    placeholder: 'Contoh: PT Kopi Rakyat Indonesia',
    required: true,
    section: 'business',
    width: 'half',
  }),
  createQuestion({
    id: 'business_category',
    type: 'select',
    title: 'Kategori Bisnis',
    description: 'Pilih sektor industri bisnis Anda.',
    required: true,
    section: 'business',
    width: 'half',
    options: [
      { label: 'Makanan & Minuman (F&B)', value: 'fnb' },
      { label: 'Ritel & E-Commerce', value: 'retail' },
      { label: 'Kesehatan & Medis', value: 'healthcare' },
      { label: 'Jasa Profesional (Konsultan, dll)', value: 'services' },
      { label: 'Properti & Real Estate', value: 'real_estate' },
      { label: 'Teknologi & SaaS', value: 'tech' },
      { label: 'Pendidikan', value: 'education' },
      { label: 'Lainnya', value: 'other' },
    ],
  }),
  createQuestion({
    id: 'business_description',
    type: 'textarea',
    title: 'Deskripsi Bisnis',
    description: 'Jelaskan secara singkat apa yang perusahaan Anda lakukan dan apa yang Anda tawarkan.',
    placeholder: 'Jelaskan bisnis utama Anda di sini...',
    required: true,
    section: 'business',
    width: 'full',
  }),
  createQuestion({
    id: 'company_size',
    type: 'select',
    title: 'Ukuran Perusahaan',
    description: 'Berapa banyak karyawan di perusahaan Anda?',
    section: 'business',
    width: 'half',
    options: [
      { label: '1 - 10 orang', value: '1-10' },
      { label: '11 - 50 orang', value: '11-50' },
      { label: '51 - 200 orang', value: '51-200' },
      { label: 'Lebih dari 200 orang', value: '200+' },
    ],
  }),
  createQuestion({
    id: 'years_in_business',
    type: 'number',
    title: 'Lama Bisnis Berjalan (Tahun)',
    placeholder: 'Contoh: 3',
    section: 'business',
    width: 'half',
  }),
  createQuestion({
    id: 'location',
    type: 'text',
    title: 'Lokasi Perusahaan',
    placeholder: 'Contoh: Jakarta Selatan, Indonesia',
    required: true,
    section: 'business',
    width: 'half',
  }),
  createQuestion({
    id: 'contact_email',
    type: 'email',
    title: 'Email Kontak Utama',
    placeholder: 'Contoh: hello@kopirakyat.com',
    required: true,
    section: 'business',
    width: 'half',
  }),
  createQuestion({
    id: 'contact_whatsapp',
    type: 'phone',
    title: 'Nomor WhatsApp Utama',
    placeholder: 'Contoh: +62 812-3456-7890',
    required: true,
    section: 'business',
    width: 'half',
  }),
  createQuestion({
    id: 'existing_website',
    type: 'url',
    title: 'Alamat Website Sekarang (Jika ada)',
    placeholder: 'Contoh: https://kopirakyat.com',
    section: 'business',
    width: 'half',
  }),

  // ================= SECTION: GOALS =================
  createQuestion({
    id: 'website_type',
    type: 'card-selector',
    title: 'Jenis website apa yang Anda butuhkan?',
    description: 'Pilih jenis website utama yang paling sesuai dengan tujuan proyek Anda.',
    required: true,
    section: 'goals',
    options: [
      { label: 'Company Profile', value: 'company_profile', description: 'Website informasi untuk mengenalkan profil perusahaan.', icon: 'Building' },
      { label: 'Landing Page', value: 'landing_page', description: 'Satu halaman fokus untuk konversi penjualan/leads.', icon: 'Layout' },
      { label: 'E-Commerce Store', value: 'ecommerce', description: 'Toko online untuk menjual produk dengan keranjang & pembayaran.', icon: 'ShoppingBag' },
      { label: 'Web Application', value: 'web_app', description: 'Sistem interaktif kompleks dengan dashboard pengguna.', icon: 'AppWindow' },
      { label: 'Booking / Reservasi', value: 'booking', description: 'Penjadwalan janji temu, kalender booking, dan tiket.', icon: 'CalendarDays' },
      { label: 'Portfolio', value: 'portfolio', description: 'Menampilkan karya kreatif, galeri foto, atau proyek.', icon: 'Briefcase' },
      { label: 'Kustom / Lainnya', value: 'other', description: 'Website unik yang tidak terdaftar di atas.', icon: 'PlusCircle' },
    ],
  }),
  // Conditional: E-commerce Specifics
  createQuestion({
    id: 'ecommerce_product_count',
    type: 'select',
    title: 'Estimasi Jumlah Produk',
    description: 'Berapa banyak produk yang akan ditampilkan di toko online?',
    required: true,
    section: 'goals',
    width: 'half',
    condition: { field: 'website_type', operator: 'equals', value: 'ecommerce' },
    options: [
      { label: '1 - 20 produk', value: '1-20' },
      { label: '21 - 100 produk', value: '21-100' },
      { label: '101 - 500 produk', value: '101-500' },
      { label: 'Lebih dari 500 produk', value: '500+' },
    ],
  }),
  createQuestion({
    id: 'ecommerce_payment_gateway',
    type: 'select',
    title: 'Metode Pembayaran Online (Payment Gateway)',
    description: 'Pilih sistem pembayaran online yang ingin Anda gunakan.',
    section: 'goals',
    width: 'half',
    condition: { field: 'website_type', operator: 'equals', value: 'ecommerce' },
    options: [
      { label: 'Midtrans (Paling direkomendasikan untuk Indonesia)', value: 'midtrans' },
      { label: 'Xendit', value: 'xendit' },
      { label: 'Stripe', value: 'stripe' },
      { label: 'PayPal', value: 'paypal' },
      { label: 'Hanya Transfer Bank Manual', value: 'manual' },
      { label: 'Lainnya', value: 'other' },
    ],
  }),
  // Conditional: Booking Specifics
  createQuestion({
    id: 'booking_type',
    type: 'select',
    title: 'Apa yang ingin di-booking?',
    required: true,
    section: 'goals',
    width: 'half',
    condition: { field: 'website_type', operator: 'equals', value: 'booking' },
    options: [
      { label: 'Jasa / Janji Temu (contoh: Salon, Konsultasi)', value: 'appointment' },
      { label: 'Kamar / Penginapan (contoh: Hotel, Villa)', value: 'accommodation' },
      { label: 'Tiket / Acara (contoh: Event, Workshop)', value: 'event' },
      { label: 'Lainnya', value: 'other' },
    ],
  }),
  // Conditional: Web App Specifics
  createQuestion({
    id: 'webapp_auth_required',
    type: 'switch',
    title: 'Membutuhkan Sistem Login Pengguna / Membership?',
    description: 'Apakah pengguna perlu mendaftar, login, dan mengelola profil mereka?',
    defaultValue: false,
    section: 'goals',
    width: 'half',
    condition: { field: 'website_type', operator: 'equals', value: 'web_app' },
  }),
  // EXTRA QUESTION: Domain & Hosting Status
  createQuestion({
    id: 'domain_status',
    type: 'radio',
    title: 'Status Kepemilikan Domain & Hosting',
    description: 'Apakah Anda sudah memiliki nama domain dan hosting untuk website ini?',
    required: true,
    section: 'goals',
    width: 'half',
    options: [
      { label: 'Sudah punya domain & hosting', value: 'have_both' },
      { label: 'Baru punya domain, butuh hosting', value: 'have_domain' },
      { label: 'Belum memiliki keduanya (butuh dibelikan)', value: 'need_both' },
    ],
  }),

  // ================= SECTION: AUDIENCE =================
  createQuestion({
    id: 'target_audience_age',
    type: 'multiselect',
    title: 'Kelompok Usia Target Audiens',
    description: 'Pilih semua kelompok usia yang menjadi target pasar utama Anda.',
    section: 'audience',
    width: 'half',
    options: [
      { label: 'Remaja (13 - 18 tahun)', value: 'teens' },
      { label: 'Dewasa Muda (19 - 25 tahun)', value: 'young_adults' },
      { label: 'Dewasa Produktif (26 - 45 tahun)', value: 'adults' },
      { label: 'Lanjut Usia (46+ tahun)', value: 'seniors' },
    ],
  }),
  createQuestion({
    id: 'target_audience_type',
    type: 'select',
    title: 'Tipe Model Bisnis Pelanggan',
    required: true,
    section: 'audience',
    width: 'half',
    options: [
      { label: 'B2C (Bisnis ke Konsumen Akhir)', value: 'b2c' },
      { label: 'B2B (Bisnis ke Perusahaan/Mitra)', value: 'b2b' },
      { label: 'Kedua B2C dan B2B', value: 'both' },
    ],
  }),
  createQuestion({
    id: 'unique_selling_point',
    type: 'textarea',
    title: 'Apa Keunggulan Utama (Unique Selling Point) Bisnis Anda?',
    description: 'Mengapa pelanggan harus memilih bisnis Anda dibandingkan kompetitor?',
    placeholder: 'Produk/jasa kami unik karena...',
    section: 'audience',
    width: 'full',
  }),
  createQuestion({
    id: 'competitors',
    type: 'textarea',
    title: 'Kompetitor Utama',
    description: 'Sebutkan 2-3 nama kompetitor atau alamat website mereka.',
    placeholder: 'Contoh: kompetitorA.com, kompetitorB.com',
    section: 'audience',
    width: 'full',
  }),

  // ================= SECTION: BRANDING =================
  createQuestion({
    id: 'has_logo',
    type: 'radio',
    title: 'Apakah Anda sudah memiliki Logo?',
    required: true,
    section: 'branding',
    width: 'half',
    options: [
      { label: 'Ya, sudah siap pakai', value: 'yes' },
      { label: 'Belum, saya butuh dibuatkan logo baru', value: 'no' },
    ],
  }),
  createQuestion({
    id: 'has_brand_guideline',
    type: 'radio',
    title: 'Apakah Anda memiliki Panduan Identitas Brand (Brand Guidelines)?',
    description: 'Meliputi palet warna, tipografi, gaya ilustrasi, dll.',
    required: true,
    section: 'branding',
    width: 'half',
    options: [
      { label: 'Ya, sudah siap pakai', value: 'yes' },
      { label: 'Belum, saya butuh panduan brand dibuatkan', value: 'no' },
    ],
  }),
  createQuestion({
    id: 'preferred_colors',
    type: 'tags',
    title: 'Pilihan Warna Preferensi',
    description: 'Tuliskan warna-warna brand Anda (tambahkan dengan koma).',
    placeholder: 'Contoh: Biru Gelap, #FF5733, Emas Hangat',
    section: 'branding',
    width: 'full',
  }),

  // ================= SECTION: FEATURES =================
  createQuestion({
    id: 'features_list',
    type: 'multiselect',
    title: 'Pilih Fitur-Fitur yang Dibutuhkan',
    description: 'Centang semua fitur fungsional yang ingin Anda pasang di website.',
    section: 'features',
    width: 'full',
    options: [
      { label: 'Formulir Kontak', value: 'contact_form', description: 'Formulir kirim pesan untuk prospek client.' },
      { label: 'Integrasi Chat WhatsApp', value: 'whatsapp_chat', description: 'Widget melayang langsung terhubung ke WA admin.' },
      { label: 'Blog / Artikel berita', value: 'blog', description: 'Halaman untuk menerbitkan konten tulisan/edukasi.' },
      { label: 'CMS (Sistem Kelola Konten)', value: 'cms', description: 'Dashboard mandiri agar Anda bisa mengedit teks/gambar sendiri.' },
      { label: 'Sistem Login & Register', value: 'auth', description: 'Sistem membership pengguna, login, & dashboard akun.' },
      { label: 'Integrasi Pembayaran Online', value: 'payment_gateway', description: 'Menerima pembayaran e-wallet, VA, & kartu kredit.' },
      { label: 'Galeri Foto/Video', value: 'gallery', description: 'Tampilan grid portofolio hasil dokumentasi.' },
      { label: 'Integrasi Google Maps', value: 'maps', description: 'Menampilkan peta lokasi toko fisik Anda.' },
      { label: 'Pendaftaran Newsletter', value: 'newsletter', description: 'Form berlangganan email info/diskon berkala.' },
      { label: 'Sistem Reservasi / Kalender', value: 'booking', description: 'Booking slot janji temu secara online.' },
      { label: 'Fitur Multi-Bahasa (Bilingual)', value: 'multi_language', description: 'Menerjemahkan konten website ke beberapa bahasa.' },
      { label: 'Optimasi SEO Dasar', value: 'seo', description: 'Pemasangan meta tags, keywords, & sitemaps Google.' },
      { label: 'Google Analytics', value: 'analytics', description: 'Melacak statistik & perilaku pengunjung situs.' },
      { label: 'Mesin Pencarian Internal', value: 'search', description: 'Kolom pencarian artikel atau produk.' },
      { label: 'Fitur Live Chat', value: 'live_chat', description: 'Widget obrolan langsung untuk support pelanggan.' },
      { label: 'Asisten / Fitur Kecerdasan AI', value: 'ai_feature', description: 'Fitur kustom berbasis AI bot.' },
    ],
  }),
  createQuestion({
    id: 'custom_features_input',
    type: 'textarea',
    title: 'Fitur Kustom Tambahan',
    description: 'Jelaskan jika ada sistem/software pihak ketiga lain yang ingin Anda sambungkan dengan website ini.',
    placeholder: 'Contoh: Menghubungkan stok website dengan software ERP/Gudang offline saya...',
    section: 'features',
    width: 'full',
  }),

  // ================= SECTION: DESIGN =================
  createQuestion({
    id: 'design_style',
    type: 'multiselect',
    title: 'Preferensi Gaya Desain Visual',
    description: 'Pilih semua gaya estetika visual yang cocok dengan brand Anda.',
    section: 'design',
    width: 'full',
    options: [
      { label: 'Minimalis & Bersih', value: 'minimal', description: 'Banyak whitespace, tipografi elegan, layout rapi.' },
      { label: 'Premium & Mewah (Luxury)', value: 'luxury', description: 'Warna emas/hitam, tekstur halus, font berkelas.' },
      { label: 'Korporat & Profesional', value: 'corporate', description: 'Struktur rapi, warna formal, tepercaya.' },
      { label: 'Modern & Futuristik', value: 'modern', description: 'Gradasi dinamis, efek mikro-interaktif modern.' },
      { label: 'Kreatif & Ceria', value: 'playful', description: 'Warna-warni cerah, elemen ilustrasi kasual.' },
      { label: 'Dark Mode Focus', value: 'dark', description: 'Tema gelap dengan sorotan warna yang kontras.' },
    ],
  }),
  createQuestion({
    id: 'reference_websites',
    type: 'textarea',
    title: 'Website Referensi Yang Disukai',
    description: 'Sebutkan 2-3 alamat website di internet yang Anda sukai tampilannya (dan jelaskan bagian mana yang Anda sukai).',
    placeholder: 'Contoh: apple.com (karena minimalis & bersih), stripe.com (karena gradasi warna & transisi halusnya)',
    section: 'design',
    width: 'full',
  }),
  createQuestion({
    id: 'animation_preference',
    type: 'select',
    title: 'Tingkat Animasi Website',
    description: 'Seberapa aktif efek animasi transisi halaman yang ingin digunakan?',
    section: 'design',
    width: 'half',
    options: [
      { label: 'Tanpa Animasi - Statis dan loading cepat', value: 'none' },
      { label: 'Sederhana - Transisi pudar halus (Sangat Direkomendasikan)', value: 'subtle' },
      { label: 'Dinamis - Animasi geser parallax, efek interaktif kompleks', value: 'dynamic' },
    ],
  }),
  createQuestion({
    id: 'project_budget',
    type: 'select',
    title: 'Rentang Anggaran Proyek (Budget)',
    description: 'Pilih estimasi anggaran yang telah Anda alokasikan (ini membantu kami memilihkan teknologi & fitur yang paling efisien).',
    required: true,
    section: 'design',
    width: 'half',
    options: [
      { label: 'Rp 5 Juta - Rp 15 Juta', value: '5m-15m' },
      { label: 'Rp 15 Juta - Rp 35 Juta', value: '15m-35m' },
      { label: 'Rp 35 Juta - Rp 75 Juta', value: '35m-75m' },
      { label: 'Di atas Rp 75 Juta', value: '75m+' },
    ],
  }),
  createQuestion({
    id: 'project_deadline',
    type: 'select',
    title: 'Target Batas Waktu Peluncuran (Deadline)',
    description: 'Kapan target website ini ingin resmi diluncurkan online?',
    required: true,
    section: 'design',
    width: 'half',
    options: [
      { label: 'Sangat Mendesak (< 3 minggu)', value: 'urgent' },
      { label: 'Standar (1 - 2 bulan)', value: 'standard' },
      { label: 'Fleksibel (3+ bulan)', value: 'flexible' },
    ],
  }),
  // EXTRA QUESTION: Pemeliharaan (Maintenance)
  createQuestion({
    id: 'website_maintenance',
    type: 'radio',
    title: 'Layanan Pemeliharaan Website (Maintenance)',
    description: 'Apakah Anda membutuhkan bantuan pemeliharaan teknis bulanan dari tim kami setelah website selesai?',
    required: true,
    section: 'design',
    width: 'half',
    options: [
      { label: 'Ya, saya butuh tim teknis untuk pemeliharaan rutin', value: 'yes' },
      { label: 'Tidak, tim kami akan mengelolanya secara mandiri', value: 'no' },
    ],
  }),

  // ================= SECTION: ASSETS =================
  createQuestion({
    id: 'assets_drive_link',
    type: 'text',
    title: 'Tautan Google Drive / Dropbox ke Aset Desain',
    description: 'Masukkan link Google Drive, Dropbox, atau OneDrive berisi logo, pedoman warna, foto produk, atau dokumen brief tambahan yang Anda miliki (Pastikan hak akses link disetel ke "Siapa saja dengan link dapat melihat/mengunduh").',
    placeholder: 'Contoh: https://drive.google.com/drive/folders/...',
    section: 'assets',
    width: 'full',
  }),
  createQuestion({
    id: 'upload_logo_files',
    type: 'file-upload',
    title: 'Unggah File Logo (Opsional)',
    description: 'Unggah file logo Anda (.svg, .ai, atau .png resolusi tinggi). Maksimal 50MB.',
    section: 'assets',
    width: 'full',
    condition: { field: 'has_logo', operator: 'equals', value: 'yes' },
  }),
  createQuestion({
    id: 'upload_brand_guidelines_files',
    type: 'file-upload',
    title: 'Unggah Dokumen Panduan Brand (Opsional)',
    description: 'Unggah file brand book atau panduan identitas visual brand Anda (.pdf, .zip). Maksimal 50MB.',
    section: 'assets',
    width: 'full',
    condition: { field: 'has_brand_guideline', operator: 'equals', value: 'yes' },
  }),
  createQuestion({
    id: 'upload_reference_assets',
    type: 'file-upload',
    title: 'Unggah Dokumen Pendukung Lain (Opsional)',
    description: 'Unggah file screenshot layout referensi, wireframe, atau dokumen brief tambahan Anda. Maksimal 50MB.',
    section: 'assets',
    width: 'full',
  }),
];
